version: '3'

services:
  mongodb:
    image: mongo:4.2
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  app:
    build: .
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env


volumes:
  mongodb_data:
